### ISSUE TITLE
Slashes in branch names

### ISSUE THREAD

**Issue by ismay** [dhis2/notes#100]
See slack conversation here: https://dhis2.slack.com/archives/C0BP0RABF/p1588249435318600

I've run into an issue with git for repos that use slashes in their branch names. We do that in some areas and it creates a conflict in some cases. In my case, I had:

- A branch called test
- Was attempting to pull a branch called test/layer-context-issue-demo

This creates an error in git as it'll have `.git/refs/remotes/origin/test` and then can't create `refs/remotes/origin/test/layer-context-issue-demo` as the former already exists.

It seems that git had already created the `test` file and was attempting to create a directory with the same name, which doesn't work (at least, not on *nix). So we can either have the test namespace for git branches, or a test branch, but not both.

I propose we just don't use slashes in branch names. Coordinating namespaces vs branch names seems too much effort, when compared to the (minor) benefit of using slashes in branch names.

Related SO answers:

- https://stackoverflow.com/a/2527452
- https://stackoverflow.com/a/2527436

**Comment by HendrikThePendric** [comment]
For years I have been using slashes and I've never had a problem, until I encountered the same issue you mention above a while ago. I would be fine with no longer using slashes in my branch names, even though I'll loose the nice folder structure in my git gui.

Alternatively we could say that all conventional commit types are "reserved namespaces", but as @ismay says, I don't think the additional mental overhead justifies the benefits.
