### ISSUE TITLE
Frontend Initiatives Meeting : June 16, 2020

### ISSUE THREAD

**Issue by amcgee** [dhis2/notes#113]
# Frontend Initiatives Meeting

**When** : Tuesday, June 16, 2020 @ 15:00 CET
**Where** : remote, let me know if you didn't get a calendar invite

# Agenda
- Initiative progress & priorities
  - [**Top Priority** - Continuous Delivery](https://github.com/dhis2/notes/issues/114)
  - Webinars and Workshops
  - Platform coverage
  - [data caching](https://github.com/dhis2/app-platform/issues/372)
  - [plugin builds](https://github.com/dhis2/app-platform/issues/375)
  - [PWA](https://github.com/dhis2/app-platform/issues/376)
- Discussions & Decisions
  - [Dependency Resolution approaches](https://github.com/dhis2/notes/issues/67)
  - ui5 successes & challenges + [major release strategy](https://github.com/dhis2/notes/issues/101)
  - How can we better push initiatives forward?

**Comment by varl** [comment]
@amcgee are there any meeting notes for this?

**Comment by amcgee** [comment]
> @amcgee are there any meeting notes for this?

There will be, haven’t had time to compile them yet

**Comment by amcgee** [comment]
In the meantime, [here is the recording](https://drive.google.com/file/d/1C0ysMCQaV-ix-j0Hk04bEDwDhXpuiYpi/view?usp=sharing)

**Comment by varl** [comment]
Great, thanks!

**Comment by amcgee** [comment]
Notes : #115
