### ISSUE TITLE
Continuous app delivery features 

### ISSUE THREAD

**Issue by Birkbjo** [dhis2/notes#114]
We want continous app delivery for 2.35, and we have to figure out what we're currently missing or haven't thought about yet. This issue will serve as an overview and discussion for potential solutions for the features we need. I will link to the respective jira-issues for the different features. 

## Top priority
It's important to figure out what kind of changes we need in the core. This often takes more time and coordination than frontend or the app-hub backend as we own that. 

### Support for multiple versions of the same app.
One of the main challenges here is to have a stable URL, while being able to differentiate between different versions. 
@amcgee proposed to have a limit of 2 versions - Stable and a preview. I think a natural solution is to just append the channel in the url. This way you could have as many versions as there are channels of that app.

- The app management app needs a way to differentiate between channels. 
- Currently I believe the core just uses the name in the manifest to generate the url. This behaviour needs to have support for multiple apps of the same name. We need to think about how the core is getting the channel. We probably don't want this in the manifest, and in that case we need changes to the installation API of apps where we can provide the channel from the app management app.

### Migrate Core apps

Core Apps needs to be migrated to the App Hub, and be tested by installing and upgrading. Should we remove Core apps from backend, and only have them in App Hub? Need to think about if preinstalled apps should be upgradable, and if so how we are going to link those apps to those installed by the App Hub.

### Verify completeness

We need to go through the process from installation to updates and verify that we have everything that is needed to move forward with continuous app delivery. 

### General updates of the App management app

In my opinion, this app is due for an overhaul but that is not something we can manage at the moment and we need to work with what we have. But it would be nice if we could at least update the header-bar.

## Notification support

It would be really nice to integrate notifications. We need two separate notification systems; one driven by the app-hub and one by the core. The former will send e-mails to managers when an app is uploaded and needs review, and to users when app status is changed. The latter is for users inside DHIS2 to let them know when an update to an app is released. 

- E-mail support in App Hub for users and managers.
   This is not that crucial at the moment, but would be nice to get in. See [Jira-issue](https://jira.dhis2.org/browse/HUB-69)
- App update notification in DHIS2.
   My initial idea is to use System messaging for this, delivered through the messaging app. The most challenging part about it is to track updates from the app-hub. See point below.
- Version tracking in core. I haven't thought much about this, but somehow the core needs a way to know when a new version is available.

**Comment by Mohammer5** [comment]
> Support for multiple versions of the same app.

@varl has introduced me to nixos and I've been reading stuff about the [nix package manager](https://nixos.org/features.html) lately. It has a very interesting way of handling packages. We might be able to adopt some of its features, as with nix you have the following advantages:

* Multiple versions
* Atomic upgrades and rollbacks
* Safe to test changes

The package manager creates folders with a hash in its name that's computed by taking several information into account. What I think about right now is: When an instance installs a new app/version, it's then built with an environment variable that tells the code what features to supports and which not. Then the built app could be stored in a folder that includes a hash in its name that includes the version of the app and the version of the instance (which indicates which features are supported). An app upgrade would create a new built app folder, which could be tested before being approved/published and rolling back would be extremely easy.

**Comment by Birkbjo** [comment]
See #117 for notes from this meeting.
