### ISSUE TITLE
Frontend Initiatives Meeting : September 30, 2020

### ISSUE THREAD

**Issue by amcgee** [dhis2/notes#126]
**When**: September 30, 2020 @ 15:00 CET
**Where** : remote, let me know if you didn't get a calendar invite

# Agenda

- Platform initiatives before 2.36 prioritization
  - Library release process - [please add comments here before the meeting](https://github.com/dhis2/notes/issues/125)
  - Port all/most app to latest platform (through step 3) - see Progressive Modernization below
  - Implement Key App Platform Features
    - [Sever Version Toggling](https://github.com/dhis2/app-platform/issues/381)
    - [State Management - what is our "standard" approach?  Moving beyond redux](https://github.com/dhis2/app-runtime/issues/444#issuecomment-622323029)
    - [Plugin builds](https://github.com/dhis2/app-platform/issues/375)
  - [CI App Hub publication](https://github.com/dhis2/app-platform/issues/330)
  - App testing & reduced tech debt - [please add comments here before the meeting](https://docs.google.com/document/d/1q_LDIZcaoGbKQ-gz1SfOJ3Fy-SeYmCn5e7n3GSCTK5Q/edit)!

## Progressive Modernization
Each app can be progressively modernized using the following procedure:

1. (if non-React) rewrite in React
2. Migrate to App Platform, using `app-runtime-adapter-d2` to support existing `d2` usage
3. Update name, version, and publish config for automated releases to App Hub
4. Upgrade components to `ui` from `material-ui` and `d2-ui`, improving `ui` widgets if missing support
5. Replace imperative data access (`fetch`, `engine.query`) with declarative data dependencies (`useDataQuery`) as close as possible to the components using the data
6. Remove `app-runtime-adapter-d2`
7. [Replace Redux or other state management with standardized state management solution (or remove app-level state)](https://github.com/dhis2/app-runtime/issues/444#issuecomment-622323029)
6. Replace Router with [App Runtime router](https://github.com/dhis2/app-platform/issues/374) (when it exists)

If I missed anything please comment here!

**Comment by JoakimSM** [comment]
Progressive Modernization step 7. I agree with Jan Henrik, I'm not convinced the benefit outweighs the effort. At least I don't think we should force every app to replace Redux (huge task). Another point is that many developers are familiar with Redux, which makes onboarding easier.
