### ISSUE TITLE
One file for one function

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/notes#15]
I know that this is a topic where MOST devs will not agree with my opinion to put every function into a separate file. I don't want to convince anyone, I just want to share my experience with both ways and want to hear your opinion about it.

# Benefits of using one file per function

### Testing functions
This is the by far more important part of separating functions into separate files.
Let's consider the following example:

```js
// fooBarBaz.js
export const foo = () => setTimeout(() => console.log('foo'), 100);
export const bar = () => setTimeout(() => console.log('bar'), 200);
export const baz = () => setTimeout(() => console.log('baz'), 300);

export const fooBarBaz = toggle => {
    foo()
    if (toggle) {
        bar();
    } else {
        baz();
    }
}
```

Testing the `fooBarBaz` function will result in checking whether the right things have been logged.
I can't stub the three functions that are being called inside `fooBarBaz` because they're in the same module. I know that I can disable timers to make this task easier, but that's not my point, just imagine the three functions do something  of async nature.

**What's the problem with testing the `console.log`s here?**
The problem is that I test the three functions twice. If there are tests in place for the three functions I don't care about what they do in the test for `fooBarBaz`, I only want to test whether the right functions are called for specific scenarios. Imagine I have multiple functins inside this file which all rely on the three functions, for every function that I test, I have to test the output of `foo`, `bar` and `buz` again!

Ideally my test would look like this:
```js
// __test__/fooBarBaz.test.js
import { fooBarBaz } from '../fooBarBaz'
import { foo } from '../fooBarBaz/foo'
import { bar } from '../fooBarBaz/bar'
import { baz } from '../fooBarBaz/baz'

jest.mock('../fooBarBaz/foo', () => ({ foo: jest.fn() }))
jest.mock('../fooBarBaz/bar', () => ({ bar: jest.fn() }))
jest.mock('../fooBarBaz/baz', () => ({ baz: jest.fn() }))

describe('fooBarBaz', () => {
    it('should call foo and bar when called with true', () => {
        fooBarBaz(true);
        expect(foo).toHaveBeenCalledTimes(1);
        expect(bar).toHaveBeenCalledTimes(1);
        expect(baz).not.toHaveBeenCalled();
    });

    it('should call foo and baz when called with false', () => {
        fooBarBaz(false);
        expect(foo).toHaveBeenCalledTimes(1);
        expect(baz).toHaveBeenCalledTimes(1);
        expect(bar).not.toHaveBeenCalled();
    });1
})
```

This way I really don't care whether the three functions return the right stuff in this test. Which is awesome, because this test isn't about the three functions anyways! **Imagine testing thunks like this!**

### Fuzzy search
When looking for a function, it's way easier to find the right file without looking through the project's file tree by just entering the file name and getting a list of files with exactly that name.

**Why is this important to me?**
When programming I don't want to spend time with the tooling. Ideally I wouldn't even spend time programming at all if I could create the solution in a faster way. So my final goal is to reduce the time I spend working on something to get it done asap.

Let's say looking for a file containing a function I'm looking for takes 3 seconds longer than just typing the functions name and hitting enter. The more complex (or complicated; look at the maintenance app) a project is, the more I will be looking for files, so if I end up looking for a function 100 times (which is not an unrealistic figure given that we're working 8 hours per day!), it's 5 minutes per day or 25 Minutes per week I spend extra which I wouldn't need to spend if looking for functions was fuzzy search friendly.

It doesn't sound like a lot and what I want to say is that there are MANY things that can be improved and this is one of those. Anyways it might take A LOT LONGER to find a function than 3 seconds if they're hidden behind an abstract file name.

### Meaningful names

If you separate functions into separate files, you'll have to think a bit more about the function's names. This will make the code more declarative, which is always good! It's a bit like TDD, it forces you to think about stuff.

That might slow you down, but in the long run, having proper function names can save a lot of time. This is basically the same reason why spending extra time for unit tests is totally ok.

## My approach to not get a messy codebase

I think this is what most people hate about separating functions into many files and I have to say it takes a bit of discipline here.

Functions that are used only inside a specific function can be outsourced to make code declarative (which is something we really want in functional programming), so reading through the code looks more like reading through a set of instructions until we read the code of the low level units. When done right, you never touch these low level units until you either need to know the implementation or you're just curious. And you only need to touch the implementation if they are the cause for bugs, otherwise you really won't have to deal with them.

So what I do is:
I extract logic from a function, create a new function with a meaningful name, describing WHAT is happening and now HOW something is done (because that's the imperative part of the code that we want to hide as much as possible), then I create a folder with the name of the function I extracted code from. In the example above, I'd create a `fooBarBaz` folder and put the three functions inside there.
I'd never have to look at the three functions until I need to know the implementation details AND they don't clutter the folder where `fooBarBaz` is inside.

Functions that are meant to be reused I always put inside a proper namespace that's inside `src/utils` or `src/lib` or `src/helpers` (personal preference, I prefer `lib` as it's faster to write).

## Conclusion
We want our code to be tested and that's good. Ideally we don't want to rewrite our code to be testable, so it makes sense to write code in a way that it feels like a "natural" code structure while still being testable. 
I never had problems with finding files with fuzzy search and I was able to test functions without having to test other functions functionality again. Which can be a tedious process when refactoring!

So what are your thoughts about this? Have you ever followed the same approach but found yourself lost in the amount of files?

## Update
This doesn't mean that I put ALL files into a separate file. Especially view files like react components often have multiple stuff inside one file in my code. Also after we've reached the conclusion that you shouldn't test EVERYTHING just for the sake of code coverage, it makes sense to group code that doesn't really need only needs test for like one or two exported functions of the whole module.

**Comment by erikarenhill** [comment]
Generally speaking I always put lots of stuff into same file when developing, but always find myself splitting up functions to separate files after some time to the benefits that you already mention (when the code works as intended I start breaking out the working parts and throw out the trash). Easier to find, re-use, test, etc. I'm positive to this

**Comment by ismay** [comment]
Interesting. I've not thought about it this deeply. I also usually put things in the same file, until it becomes too complex. At that point I try to abstract the contents to different files to make it easier to understand. I think I mainly first try to optimise what I write so it's easy to understand, and whether or not I put it in the same file follows from that usually.

**Comment by Birkbjo** [comment]
I must start by saying I really disagree with this.

I believe most of your arguments are just symptoms of your way of work and editor. I don't want to be a smug and say "just use VSCode" but really, most of your complaints about searching for functions would evaporate if you used such an editor. There's probably a plugin to find declarations and implementations for vim as well.

For me, the constant context switching of moving back and forth between files are much more annoying and detrimental to my flow than anything else, and one of my main annoyances when working with redux, as you constantly have like 4-5 files to work on when creating a feature. Imagine having 10+ files for a simple async call. I don't know what lengths you would go to, but e.g having one file for each actionCreator would be my biggest nightmare.

Regarding testing you could use something like https://github.com/speedskater/babel-plugin-rewire , or in these cases you could extract the shared functions to its own module, as most of the time such shared functions go into the category of "utils/helpers/lib", which tend to not be of async-nature. 

I agree that we should split complex logic into separate files, and I know where you are coming from if you have been deep down in the maintenance app. There's pieces of code and components that are way too big and complex. But we have not refactored this everywhere, as then we would've done nothing else than refactoring.

I'm a proponent of splitting files into "natural" pieces of code. E.g actionCreators for this module/functionality in one file. Some API-functions in one file, some related utils-files in another etc. Most of these functions share or belong together. Of course we could have some standards of how to structure code (by domain, ducks, or rails-style), but I believe trying to enforce stricter rules than that just leads to developer fatigue. I also believe code structure depends a lot on the app/context, and is not something that should blindly be applied everywhere.

As developers we inherently have a lot of opinions about everything, and it's impossible to get developers to agree on any one simple thing. I prefer "utils" by the way.

**Comment by Mohammer5** [comment]
@Birkbjo 

> I believe trying to enforce stricter rules than that just leads to developer fatigue
I'm not trying to enforce any rules :) Just share my experience so far. Happy to hear that you have some really good and valid arguments! I don't even want to convince anyone, just want to talk about it :) maybe in the end I'm convinced to go the opposite way.

> most of your complaints about searching for functions would evaporate if you used such an editor.
Yes, it's a symptom of using vim. But forcing an IDE for one specific feature is wrong IMO. With most other things I'm way faster with vim and it should always be a devs choice to use tools of their liking. Especially with open source projects! And vim is awesome ;)

> the constant context switching of moving back and forth between files are much more annoying and detrimental to my flow than anything else
This is very interesting, because I don't experience it that way at all. But this might be another IDE thing where I can have 8 splits opened easily in vim and navigate seamlessly while still seeing the whole content of every file I have opened. Or maybe it's because I'm working mostly on the same two or three files and don't even want to think about everything else. I do understand that people can be very frustrated with one func per file when it's contrary to the philosophy of their tools.

> Regarding testing you could use something like https://github.com/speedskater/babel-plugin-rewire , or in these cases you could extract the shared functions to its own module
This is VERY interesting, haven't heard of this one before! I like to have all action creators in one file but never had the feeling that I can test thunks if they were in the same file. The tests would look really ugly though..

Maybe I went a bit too opinionated on the whole topic. I definitely agree that grouping functions is a good thing but it needs thoughts as well so you won't end up with maintenance-hell :D

### Conclusion for myself so far:
1. Use vim fzf, maybe that'll help with fuzzy finding
2. Play around with `babel-plugin-rewire`

**Comment by ismay** [comment]
I've used https://github.com/dmitry-zaets/redux-mock-store and https://www.npmjs.com/package/nock in the past for testing thunks. At the time that worked well for me.

**Comment by varl** [comment]
I like that you are surfing on waves not in the main stream, @Mohammer5. 🏄

My main concern is that depending on what rules you use for grouping and where you decide to cut the file will influence on how the code base is structured and how the whole is understood by its developers.

I see from your comments that you have thought about this, and how I understand the arguments it is about being able to compose bigger things from smaller things, and these smaller things should be kept in isolation.

I think that is a safe zone to be in; on the flip side, the danger zone is when a function which is seemingly "large" or "hard to test" is cut into smaller pieces. The effect is the same if it is done in the name of **Composabililty** or in the name of **Testability**[1]:

>Of course, this also meant that functions no longer encapsulated algorithms. It was no longer possible to reason about the execution context of a line of code in terms of the lines that precede and follow it in execution, since those lines of code are no longer adjacent to the one you are concerned about.

And on a higher level this sort of behaviour has a detrimental effect on the system, put succinctly by the author of [1]:

>If you find your testers splitting up functions to support the testing process, you’re destroying your system architecture and code comprehension along with it. Test at a coarser level of granularity.

[1] [Why-Most-Unit-Testing-is-Waste.pdf](https://github.com/dhis2/notes/files/2870628/Why-Most-Unit-Testing-is-Waste.pdf)

The author has chosen something of a Fireball as a title for the article. Never-the-less I find it very interesting to read through and recommend it.

**Comment by varl** [comment]
Regarding the `utils`/`lib`/`helpers`:

>Functions that are meant to be reused I always put inside a proper namespace that's inside `src/utils` or `src/lib` or `src/helpers` (personal preference, I prefer `lib` as it's faster to write).

>I prefer "utils" by the way.

I would argue that putting functions inside of these catch-all buckets does not serve the idea to make functions first-class citizens of the application architecture. However, I may have misunderstood the scope  if we are talking about the "I don't know where this logic belongs so it goes in the bucket"-functions. 

If the context of the discussion is how to organize the utility namespace, then we have code which use the structure: `src/util/map-reduce/index.js`.

In other places it would be `src/util/map-reduce.js` or even just put inside `src/util/index.js`. I don't think it matters that much.

What matters to me is that a function _does something_ and that I can understand what it does when I read it. I might not have to bother with every single implementation detail but if I find myself jumping from one file to another file just to understand a `for`-loop then there is something funky in the code base as far as I am concerned.

To switch gears a bit... ⚙️ 

How would the structure of an application look if the functions _which does something_ were promoted to first-class citizens and not relegated to a utility-folder or hidden away inside of a component module?

The logic could be easily separated out from the presentation components, tested in isolation, _and_ be discoverable without having to be matched to a function name or a file. The code base could be navigated based on its structure instead.

And besides, is there really that much of a difference to search for a **file** name or a **function** name? They are both strings... 🍡

**Comment by varl** [comment]
>Regarding the meaningful names, it does not stop someone from importing it as something else, in that case only named exports would be allowed. But that would also make sense since it would be named the same way throughout all apps, and not imported as foo in one app and baz in another.

If you are using default exports it wouldn't matter at all if it is imported as `foo` in one app and `baz` in another since the name doesn't leave the module.

You can have a function such as `export default function Foobar() {}` in one version and then change it to `export default function Fuzbuz () {}` the next version, and none of the consumers of that module would have to change anything. If you used named exports exclusively, then that would be a breaking change.

The flip-side is that if you use named exports then scanning code using ack/grep is a lot easier and fix the breakages.

I read this article from a fellow who has decided to stop using default exports completely, though I find some of his reasons counter-intuitive, for example:

>Side trips slow down development. Whenever you have to stop and look something up in the middle of coding, I call that a side trip. Side trips are sometimes necessary but there are a lot of unnecessary side trips that can slow things down. I try to write code that eliminates the need for side trips.[1]

When I have to open another file to see what the named exports are, that's a side trip. If that file is in `node_modules` it is more like a detour through the nine rings of Hell. 🔥 This relates to some of the arguments in this thread as well.

[1] https://humanwhocodes.com/blog/2019/01/stop-using-default-exports-javascript-module/

**Comment by varl** [comment]
I don't think that the developers' choice of development environment should be drive the decisions on how any code base is structured and designed.

**Comment by ismay** [comment]
Maybe what this demonstrates is just also that good DX for vim users tends to be different from good DX for atom/sublime/vscode users. I don't know how much vim users use something like nerdtree, but I can imagine that the absence of a file tree makes for a different way of navigating around the codebase for instance.

**Comment by erikarenhill** [comment]
For the record I use VSCode. I find that breaking up functions to separate files is comparable to keeping one class in one file in the OOP-world which of course is what you want. But then it doesn't have to be all black or white. As @Birkbjo picks as example, I would also prefer tiny selectors or action creators to be grouped into one file.

This discussion could easily be heading towards project structure in terms of for example where reducers, selectors, action-creators etc should be placed. Near and isolated to the part of application and components using it, or more globally like all reducers in the same reducer directory.
