### ISSUE TITLE
[spec] Alerts Service (WORK IN PROGRESS)

### ISSUE THREAD

**Issue by amcgee** [dhis2/notes#152]
This is a placeholder for an Alerts Service specification, including both `app-runtime` and `app-adapter` components

**Comment by HendrikThePendric** [comment]
We've introduced an `alers-service` in `app-runtime` https://github.com/dhis2/app-runtime/pull/657 and we've included some components in the app-shell to actually show these https://github.com/dhis2/app-platform/pull/486.

This issue can be closed now.
