### ISSUE TITLE
Frontend Initiatives Meeting: November 11, 2020

### ISSUE THREAD

**Issue by varl** [dhis2/notes#155]
When: November 11, 2020 @ 15:00 CET
Where : remote, let me know if you didn't get a calendar invite

# Agenda

- Quick general updates:
  - Migration to JIRA is progressing.
  - There was a Cypress meeting yesterday and [the minutes are available](https://github.com/dhis2/notes/pull/140), feel free to comment even if you weren't in the meeting.
- Updates from active working groups
- [Prioritization for ui issues](https://github.com/dhis2/notes/issues/125)
  - The proposal is to handle prioritization of library issues as part of the main prioritization process in JIRA. This allows better visibility across app and library dependencies, better visibility for the project about what work is done, etc.
- Migrating d2-ui components
- Tech debt review

**Comment by Mohammer5** [comment]
> Prioritization for ui issues [...] The proposal is to handle prioritization in JIRA

Cross-project proposal: Organize and prioritize features (includes tasks, but not bugs) through epics and let a couple of devs work on the same epic at the same time.
* Epics should consist of issues of **one** topic
  * so we don't get "_fix all bugs_" or "_improve ux_* issues, but instead "_improve ux of program secton_" in the maintenance app for example
* Follow-up to the good experience @HendrikThePendric, @ismay and I had when working on the sms configuration app together
* Multiple devs know the code
* We wouldn't have to prioritize that many individual issues (only bugs, epics and a few stray features)

**Comment by varl** [comment]
Closed by: https://github.com/dhis2/notes/pull/156
