### ISSUE TITLE
jest-cucumber?

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/notes#161]
> > My preference would be to use feature files, but I'm outnumbered
> 
> I know it's in jest (💯 pun credits for me), but I wouldn't want to force a decision just through numbers. I would prefer to go with the best solution, even if the majority disagrees. I wouldn't mind taking a deeper look and weighing the pros/cons, there could be things I'm overlooking.
> 
> _Originally posted by @ismay in https://github.com/dhis2/ui/pull/130#issuecomment-697380529_

Discussion about jest cucumber

**Comment by varl** [comment]
We decided against Cucumber in Jest.
