### ISSUE TITLE
Icon sizes

### ISSUE THREAD

**Issue by ismay** [dhis2/notes#162]
Branching off of https://github.com/dhis2/ui/pull/284 to discuss the sizes we'll ship with our icons.

**Comment by varl** [comment]
This doesn't match the proposals in other issues and PRs, for example this one: https://github.com/dhis2/ui/pull/313

**Comment by ismay** [comment]
You're right. Current proposal that everyone seems to agree on is fixed sizes, included in the icon name (so no size prop).

We could consider allowing icons to be scaled as an escape hatch for devs that need other sizes than what we provide. There wouldn't be a scaling problem as they're vector graphics. Only downside might be that the amount of detail could be unappropriate for the rendered size. But that seems like the devs responsibility in that case. I think it'd be nice to not block that route.
