### ISSUE TITLE
Remove codeclimate from PR checks

### ISSUE THREAD

**Issue by ismay** [dhis2/notes#17]
@dhis2/dhis2-front-end 

Short summary of the discussion on codeclimate on slack:

> do any teams rely on the codeclimate checks on PRs? In the couple of repos I've committed to, all I'm getting from it are duplicate code warnings that don't seem to add much value. If no one uses it, it might be good to remove those checks. (ismay)

- Apparently it's not possible to focus on real duplication, so we're getting a lot of false positives, especially from test files
- There does not seem to be a way to configure this check more precisely

My proposal is to remove codeclimate as my opinion is that code quality is better checked with good reviews (and maybe some linting for tiny, obvious things), and that it's not that good to merge PRs with failing tests (because why have the test then).

I'm opening this issue so everyone can weigh in on whether or not they agree with the above, and also to allow us to discuss what the intended purpose was of the codeclimate checks and see if we can address that some other way.

**Comment by varl** [comment]
@vilkg has set up SonarQube, which runs on our own servers, so we can configure that to our hearts content to get an idea over the (self-defined) quality of our software. 

SonarQube can (not sure if we have the developer edition) be integrated with GitHub as well, so we could do analysis on PRs.

Check out an example for the maintenance app: https://ci.dhis2.org/sonarqube/dashboard?id=maintenance-app

**Comment by HendrikThePendric** [comment]
First off, I am 👍 for getting rid of CodeClimate.

But in order to make this a conscientious decision, perhaps we could review the [CodeClimate report for the usage-analytics-app](https://codeclimate.com/github/dhis2/usage-analytics-app), which I've "tweaked" to the best of my ability....

As far as I could tell, there are two options for tweaking:
- excluding files / file-patterns
- disabling rules

For the usage-analytics-app, I opted to keep all the rules enabled, but to exclude some files, the `.codeclimate.yml` looks like this:
```yml
exclude_patterns:
    - 'src/__mockData__/'
    - 'config/'
    - 'scripts/build.js'
    - 'src/serviceWorker.js'
    - '**/*.test.js'
```
So this basically skips all test-related files and the files generated by CRA.

When reviewing the report and setup options, my **personal** interpretation is this:

1. Fully ignoring the test files via config is not a good thing, these could also have shortcomings
2. The alternative, completely switching off the duplication checks via config, felt like an even worse option.
3. In the report, I am still getting quite a few duplication errors. Upon review, I would classify all of these as false positives.
4. The only GOOD thing I can find in the CodeClimate report are the Code Smells reports I am seeing. These three parts of the code-base could probably do with some refactoring to make things a bit more simple....

So, if others agree with my conclusion, that the only benefit that CodeClimate brings to the table is the CodeSmell aspect, then perhaps we could ditch CodeClimate, and replace the CodeSmell aspect by some smart ESLint rules (as @ismay suggested).

I think these would be good candidate ESLint rules:
`complexity`
`max-statements`
`max-lines-per-function`
etc....

**Comment by ismay** [comment]
> But in order to make this a conscientious decision, perhaps we could review the [CodeClimate report for the usage-analytics-app](https://codeclimate.com/github/dhis2/usage-analytics-app), which I've "tweaked" to the best of my ability....

I took a look at it. The part of it that seems useful to me is the test coverage, I've found coverage reports helpful sometimes for finding untested areas of your code. I find the coveralls ui more intuitive for that though (but opinions might differ on that of course).

> I think these would be good candidate ESLint rules: `complexity` `max-statements` `max-lines-per-function` etc....

Yeah seems like they'd do pretty much the same thing. Sounds good to me. Nice that we could then also just use existing tooling, which runs locally as well. Seems like a net improvement.

So it seems like we could basically do anything codeclimate does ourselves. There haven't been any other usecases discussed that we'd break by removing this, so I guess we can start removing it?

**Comment by varl** [comment]
Jest has built-in coverage reports with [`--coverage`](https://jestjs.io/docs/en/cli#coverage).

**Comment by ismay** [comment]
True, but I do find those less friendly than a coveralls report. But yeah, it does contain basically the same information. Whether or not we want a code coverage reporting tool is probably a whole other discussion 😋

**Comment by Philip-Larsen-Donnelly** [comment]
I'd be keen to see if we could get all of the quality checks we need centralised, as much as possible, and tailor the rules to our quality standards. To that end I would be happy for us to remove CodeClimate and instead put some focus on harmonising our use of Sonarqube and the rules we define there.
Unfortunately, we don't have the developer edition, but it might (should) still be possible to analyse PRs. At the very least we will analyse merges.

**Comment by ismay** [comment]
> I'd be keen to see if we could get all of the quality checks we need centralised, as much as possible, and tailor the rules to our quality standards. To that end I would be happy for us to remove CodeClimate and instead put some focus on harmonising our use of Sonarqube and the rules we define there.

Sounds good! We haven't had any objections, so I think at this point it's safe to start removing codeclimate from our repos. I'll put a last notice on slack, and I guess that unless people object to it there we can start removing it from our repos 😊

**Comment by jenniferarnesen** [comment]
I'm fine with removing it, and support Phil's suggestion above

**Comment by HendrikThePendric** [comment]
We will replace the CodeClimate CodeSmell feature with additional ESLint rules. But I don't quite understand how we will replace the Coverage part. I know that the actual coverage report is generated anyway, but I do think it is also nice to be able to place some badges in the README. How would we do this? Something like this? https://www.npmjs.com/package/jest-coverage-badges

**Comment by amcgee** [comment]
[CodeCov](https://codecov.io/) and [Coveralls](https://coveralls.io/) are
good options too.  I agree having a badge is nice, but to me what's even
more important is being able to visualize the diff of code coverage levels
in a PR.

**Comment by ismay** [comment]
> but to me what's even more important is being able to visualize the diff of code coverage levels in a PR.

Yeah that's a good point. Jest's console output does not make it very inviting to explore what changed in your code coverage.

> We will replace the CodeClimate CodeSmell feature with additional ESLint rules. But I don't quite understand how we will replace the Coverage part. I know that the actual coverage report is generated anyway, but I do think it is also nice to be able to place some badges in the README. How would we do this?

I'd also suggest what @amcgee's suggesting. I don't have experience with codecov, but these kinds of services are a nice way to keep track of and visualize test coverage. As an example, this is what you'd get when using coveralls: https://coveralls.io/github/ismay/stylelint-no-unsupported-browser-features?branch=master

**Comment by varl** [comment]
Bear in mind that we might be able to get the functionality out of SonarQube, so we need to look in to that before we switch CodeClimate for some other service and miss out on what @Philip-Larsen-Donnelly needs as the QA lead.

If we cannot get what we as devs need after trying to implement SonarQube, we can look into alternative services while still making sure that we get more-or-less the same results.

**Comment by varl** [comment]
I've removed all the old code climate webhooks, I'll talk to @vilkg to set up sonarqube.
