### ISSUE TITLE
Move to a pure javascript based SSG

### ISSUE THREAD

**Issue by ismay** [dhis2/notes#196]
I know that jekyll is the default for GH pages, and that this task will probably (and understandably) end up at the bottom of the priority list, but I find working with jekyll to be quite painful. As a team that uses almost exclusively javascript based tooling, getting a ruby based tool working properly on my system requires a ton of effort. Configuring syntax highlighting, updating dependencies, it all takes way more time than it should.

In my own experience there are plenty of viable alternatives that run exclusively on js and are better maintained and easier to work with. Should we have the time, I would love to get rid of jekyll. and think it would greatly improve maintainability of this project.

**Comment by varl** [comment]
@deboragaleano has done this with dhis2/developer-portal.
