### ISSUE TITLE
Which future syntax do we want to use in our js?

### ISSUE THREAD

**Issue by ismay** [dhis2/notes#23]
I was going to open a jira issue for this, but it seemed slightly too philosophical for that. I'm wondering what level of the ecmascript proposals we officially want to use in our apps. As in, do we allow any and all future syntax? Do we only use syntax that's highly likely to not have to be changed?

I'm asking because we're using some future syntax in our apps, but I'm not aware of any dhis2 stance on what we do and don't use. So it seems to be up to the app devs. I think it would be good to have some clarity on that by sharing/discussing our stance.

For reference, the stages:

> Stage 0 “strawman” — The starting point for all proposals. These can change significantly before advancing to the next stage. There is no acceptance criteria and anyone can make a new proposal for this stage. There doesn’t need to be any implementation and the spec isn’t held to any standard. This stage is intended to start a discussion about the feature. There are currently over twenty stage 0 proposals.

> Stage 1 “proposal” — An actual formal proposal. These require a “champion”(i.e. a member of TC39 committee). At this stage the API should be well thought out and any potential implementation challenges should be outlined. At this stage, a polyfill is developed and demos produced. Major changes might happen after this stage, so use with caution. Proposals at this stage include the long-awaited Observables type and the Promise.try function.

> Stage 2 “draft” — At this stage the syntax is precisely described using the formal TC39 spec language. Minor editorial changes might still happen after this stage, but the specification should be complete enough not to need major revisions. If a proposal makes it this far, it’s a good bet that the committee expects the feature to be included eventually.

> Stage 3 “candidate” — The proposal has approved and further changes will only occur at the request of implementation authors. Here is where you can expect implementation to begin in JavaScript engines. Polyfills for proposals at this stage are safe to use without worry.

> Stage 4 “finished” — Indicates that the proposal has been accepted and the specification has been merged with the main JavaScript spec. No further changes are expected. JavaScript engines are expected to ship their implementations. As of October 2017 there are nine finished proposals, most notably async functions.

> From https://blog.logrocket.com/interesting-ecmascript-2017-proposals-163b787cf27c

Related to this we might also have to discuss APIs actually.

**Comment by varl** [comment]
Stage 4!

**Comment by ismay** [comment]
> Stage 4!

Yeah I'd prefer the more conservative approach too. I've used quite futuristic syntax in projects before, but to me it seemed that it reduced portability, potentially had to be refactored if the spec didn't make it, and at times could confuse others who weren't yet familiar with the spec. Even more so for big software projects, where refactoring costs are bigger and the codebase needs to be accessible for different devs.
