### ISSUE TITLE
Using storybook/cypress/gherkin for our component libs

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/notes#42]
# What do I want to achieve?

Currently, there are no specs defined for our front end libs, the styleguide is still incomplete and we have little to no documentation for our components. It's very good to have storybook as devs now can see how to use components in isolation and what it'll look like before using them in the apps. but I think that's not good enough. When we encounter a bug, we fix the bug and create a test case in JIRA; which - to me - is kind of out of ours minds when we're done working on a bug ticket.

If we use the Gherkin syntax to define specs, we'll have the specs together with the code, they're codified and versioned, so we can adjust them easily. It will also make sure that out components are functional as they'll be tested in a browser, not just with jest => Rendering components will throw real errors.

If we go with this method, we'll have thw following three things:
1. Specifications
2. Documentation
3. Functional tests

# How will the test code look like?

In the `ui-core` repo, you can see the storybook in action, it's already part of the master branch, just clone the repo and run `yarn start`.

I have prepared a draft PR to demo what it looks like to combine cypress (without cucumber) and storybook, you can find it here: https://github.com/dhis2/ui-core/pull/179 (don't forget to `yarn install`)
After running `yarn start` to spin up the storybook, run `npx cypress open`, where you will see a few prepared test cases.

I also have created a non-working sketch of what the cucumber features/step definitions would look like when the cypress-cucumber plugin comes into play, you can check it out here: https://github.com/Mohammer5/ui-forms
Nothing is working, so the code is really just a sketch, so once you've played around with my draft PR for the `ui-core` repo, have a look into this one and checkout the code to see how gherkin takes the tests/specs to the next level.

# What to discuss

This approach would change our workflow when it comes to component libraries. So I'm not sure you guys are on board with this.

What do you think of this solution?
Is there something I might have overlooked?
Do you prefer an alternative like cucumber.js with Selenium?

**Comment by ismay** [comment]
I like your proposal. The most important parts to me would be:

- Storybook as our living style guide
- Cypress for integration tests (seems to be well received by the community)
- Some type of visual regression testing (say with [percy.io](https://docs.percy.io/docs/storybook) for example)

To me it seems like that would make our lives easier as devs, help us catch regressions quicker, write more robust code, etc.

I'm not sold on the gherkin/cucumber part though. I understand why you'd include the cucumber tests, to have the specifications codified and separated from the integration tests. That seems like a nice way to keep the integration test implementation separate from the specs.

But it also feels like a slightly awkward and elaborate ritual just to codify requirements to me. I hope it won't turn out to be something that gets annoying and time-consuming and therefore underused. I can also imagine that mentioning the requirements directly in the assertions of the integration tests would make it clear what the requirements are. But maybe that ruffles some BDD feathers I don't know. Would like to know what you and the rest think!

**Comment by Mohammer5** [comment]
I can only speak from my own experience so far and I haven't used cucumber in any large project yet, I only played around with it a little.

What I liked about it is that anyone can propose specs/features as it's relatively easy to learn the language. And using PRs for adding specs would be a nice way to include all devs into the decision what a feature should look like before we even start coding.

But I don't care too much about the cucumber part (although I like it). I think the cypress + storybook combination already add a lot of benefits! It will add working examples of the app which anyone can try in isolation without us having to create demo pages.

**Comment by Mohammer5** [comment]
Already in use
