### ISSUE TITLE
Api url discovery

### ISSUE THREAD

**Issue by ismay** [dhis2/notes#43]
I was (am) working on https://jira.dhis2.org/browse/TECH-160, which is about rewriting d2-manifest. In going through the requirements I talked about it with @amcgee and @varl. Most of the discussion centered on api discovery, as we're currently using the app manifest for that.

After discussing it for a bit, we sort of arrived at the following proposal:

1. Deprecate d2-manifest (there are already tools for generating standard app manifests, or it could just be written by hand)
2. Move to env vars for passing a (relative or absolute) url for api discovery, e.g. something like `DHIS2_API_URL`
3. Eventually allow users to specify a specific dhis2 backend in the login screen (with optional default from the env var)

This would strip out the non-standard parts of the app manifest, and would (in my opinion) be a more common way to point a built app to the api. Point 3. is sort of separate, but came up in the discussion as well, and is sort of related.

@varl replied:

> 1. deprecating d2-manifest is ok with the verification that we can install apps without it and that they still work
> 2. this is preferable to me as it is simple to use and override for local environments. for prod builds we can set it globally in the build script too to make sure that we never screw it up by accident
> 3. i need to think about this; it's a cool idea for many reasons and opens up many interesting ways to test an app against multiple different backends very easily in addition to new constellations of server deployments

On slack, see https://dhis2.slack.com/archives/CHENB0272/p1555337332014700 and https://dhis2.slack.com/archives/G451J9KGR/p1555401210055300 for the discussion

I'm creating this issue to track what we've discussed, so that we can come back to it when there's new info. And to allow others to give feedback on the idea as well of course.

**Comment by varl** [comment]
A bit of more information about this can be found in #53.

**Comment by amcgee** [comment]
This has been implemented in the App Platform, so closing this issue 🎉
