### ISSUE TITLE
Notes on unejected apps

### ISSUE THREAD

**Issue by ismay** [dhis2/notes#53]
Maybe this could eventually go in the gotchas, but I'm opening an issue first so there's room for discussion/feedback.

Most have probably seen the 'uneject' PRs in some apps, or seen discussion on slack about 'unejecting' apps back to CRA. Since I got a couple of question about unejected apps when in Oslo, I thought it'd be good to summarise the most important changes.

These are the apps that were unejected:

- https://github.com/dhis2/usage-analytics-app
- https://github.com/dhis2/messaging-app
- https://github.com/dhis2/data-quality-app
- https://github.com/dhis2/import-export-app
- https://github.com/dhis2/data-administration-app
- https://github.com/dhis2/user-app

In general I tried to stay as close as possible to the original codebase. There were some apps with small bugs that I fixed whilst unejecting, but other than that they should be quite similar after unejecting.

However, some changes were necessary to allow the apps to work with CRA. After unejecting I also updated the dependencies and enabled greenkeeper, and that also sometimes required changes. Also, some things emerged that after discussing seemed like a better approach for our new apps. I'll list the important changes so you don't have to go digging through the PRs:

### 1. Moving to .env files for API discovery

I ran into an issue with the manifest.webapp being used for api discovery, and after discussing it, using env vars seemed like a better approach. With CRA they can be set for `production`, `development` and `test`. They can also be overridden locally. So for example, for production we're setting:

```ini
# .env.production

# Prepended to asset paths in the generated index.html. This allows the app to still work
# when served from a nested path, like on the play server
PUBLIC_URL="."

# The url used for api discovery. Usually concatenated with '/api' to construct the base path for
# api requests like so: `${REACT_APP_DHIS2_BASE_URL}/api/`,
REACT_APP_DHIS2_BASE_URL=".."

REACT_APP_DHIS2_AUTHORIZATION=
```

If you want to override anything locally, you can do so with a `.env.production.local` file, which is gitignored. So instead of adding these settings to the manifest and fetching that from the client, these variables are now baked into our code.

For PWAs there could still be a need for a manifest btw, but you can just place a static one in the `/public` folder. For more info see: https://facebook.github.io/create-react-app/docs/adding-custom-environment-variables.

### 2. Enabling cli-style

Since we decided to move ahead with cli-style on master, I've added this as well to the apps I was working on. I've basically followed the readme on setting it up and adding the hooks: https://github.com/dhis2/cli-style#setup-for-javascript-project, and installed the config files.

I've also added a npm script to run `"d2-style js check --all"` on travis. Just to make sure that code that violates the standards doesn't end up in the repo (or it at least shows you that something is wrong).

### Small changes

Other than the changes above, I've also made the following small changes:

- Travis builds on `lts/*`, instead of a fixed node version
- Unused dependencies were removed
- Tried to align the READMEs, since they were all quite different
- Added the same favicons everywhere (the dhis2 logo)

Those are the main things that changed for the unejected apps. So as said before, I tried to keep things as similar as possible, but if you encounter anything, or something seems weird, let me know!

**Comment by ismay** [comment]
I've also encountered some minor issues whilst unejecting apps. I'll be opening issues in their repos to track those as well.

**Comment by ismay** [comment]
These apps still need to be unejected:

https://github.com/dhis2/reports-app
https://github.com/dhis2/data-visualizer-app

For the reports-app it'd be better to uneject it after the app-shell is done (due to styled-jsx). The data-visualizer-app might be easier to uneject for the analytics team.

These are apps that weren't ever CRA apps as far as I could tell:

https://github.com/dhis2/maintenance-app 
https://github.com/dhis2/gis-app
https://github.com/dhis2/settings-app
https://github.com/dhis2/tracker-capture-app
https://github.com/dhis2/pivot-tables-app
https://github.com/dhis2/app-management-app
https://github.com/dhis2/charts-app
https://github.com/dhis2/translations-app
https://github.com/dhis2/event-capture-app
https://github.com/dhis2/maps-app
https://github.com/dhis2/data-quality-app-who
https://github.com/dhis2/dashboard-app
https://github.com/dhis2/interpretation-app
https://github.com/dhis2/datastore-app
https://github.com/dhis2/event-reports-app
https://github.com/dhis2/user-profile-app
https://github.com/dhis2/event-charts-app
https://github.com/dhis2/cache-cleaner-app
https://github.com/dhis2/scheduler-app
https://github.com/dhis2/menu-management-app
https://github.com/dhis2/who-immunization-analysis-app

**Comment by varl** [comment]
Thanks for writing down all of the apps! That helped a lot when tracking down a bug when the **2.31.4** release was cut.

In `.travis.yml` the deploy-build setting needs to be:

```
deploy:
    - provider: script
      script: npx --package @dhis2/deploy-build deploy-build
      skip_cleanup: true
      on:
          all_branches: true
```

On the un-ejected apps the setting `deploy.on.tags` was set to `false`, which stops the release script dead since the tag for e.g. **2.31.4** is never built and the final WAR build fails.

**Comment by ismay** [comment]
Ah damn, sorry about that. I took the travis config from another repo, but I think that that might have been a library then? Anyway, thanks for addressing it!

**Comment by varl** [comment]
@ismay Don't sweat it; I reviewed it and missed it too. Yes, that might've been a library.

Figured I'd document it here since that was most definitely a gotcha!
