### ISSUE TITLE
Create a general channel on gitter

### ISSUE THREAD

**Issue by aucampia** [dhis2/notes#68]
Currently there is no general dhis2 channel on gitter (under dhis2 community: https://gitter.im/dhis2/home), please create one.

**Comment by varl** [comment]
HI @aucampia! 

We do not use Gitter to communicate with our community. There is a general DHIS2 community at https://community.dhis2.org/ full of implementers, developers, users, etc.

May I ask what you need the Gitter channel for?

**Comment by varl** [comment]
This is cross-posted to https://community.dhis2.org/t/general-gitter-channel/37131. Closing this.
