### ISSUE TITLE
Customizing index.html for app created with `d2 app scripts init dhis2-app`

### ISSUE THREAD

**Issue by aucampia** [dhis2/notes#69]
Currently if I create an app with `d2 app scripts init dhis2-app` the index.html comes from https://github.com/dhis2/app-platform/tree/master/shell - this directory is copied. It seems there is some (undocumented AFAICT) provision for copying from a different location - but I cannot see any way of altering just parts of this. I think this is an indication that this approach is not ideal, and as mentioned in another issue it would be better probably to not do this and rather look at best practices used by other frameworks, but given things are the way they are is there some way to customize index.html found here https://github.com/dhis2/app-platform/blob/master/shell/public/index.html ?

**Comment by varl** [comment]
Hi @aucampia!

Thanks for getting involved in the discussion about the application platform.

What is your use case for modifying the `index.html` which hosts your application? We consider it a springboard to launch your app in lieu of a better bootstrap process so you generally should not have to think about what's in there as it is centrally managed.

**Comment by amcgee** [comment]
Hi @aucampia - as @varl said, thanks for getting involved!

I'd also love to hear what the use case is for modifying `index.html` - we intentionally restrict customization of these core application components, but we're open to exposing controlled configurability if there are compelling use cases.

I'll respond in more detail to the other issue you opened - dhis2/app-platform#96

**Comment by varl** [comment]
Closing this as it belongs in dhis2/app-platform#96.
