### ISSUE TITLE
Frontend merge strategy and workflow

### ISSUE THREAD

**Issue by varl** [dhis2/notes#72]
> _Outcome of FEDB: #70_

## Trial

We will start using the "rebase-merge" workflow on a couple of different repositories before deciding if it works for us or not.

## Background and discussion

Currently we use "squash-merge" as our default strategy, and we also use `next` branches to merge multiple fixes/features to `master` at the same time.

There is a significant downside of this in terms of how the changelogs are generated.

This commit was merged from `next` to `master` to release version 3.0.0 of `@dhis2/ui-core`:
https://github.com/dhis2/ui-core/commit/6df182bdbb1de8b80d76ac7677a1a37478aa8da6

The commit message itself is nicely formatted and has a list of all the changes, but the CHANGELOG is quite sparse:
https://github.com/dhis2/ui-core/blob/master/CHANGELOG.md#300-2019-06-06

It contains a single `chore` and lists the breaking change. In order to get all the commits into the changelog, they must land on `master` as well. We can use the `[skip ci]`/`[defer release]` tag to do that when there are two or three PRs to merge after eachother, but when there are
[69 commits bundled into one release](https://github.com/dhis2/ui-core/pull/430/commits) that is not an option.

## Requirements

Given that we want:

- Linear history on `master` (no merge commits)
- One commit per feature/fix
- Option for bundling changes for a release
- Precise changelogs

## Rebase and merge strategy

Then the "rebase-merge" strategy is a good option:

- We can enforce that _all_ commits on a branch are semantic commits as as status check (using **probot-semantic-pull-requests** currently enabled in all repositories).

- No need to ever provide a manual commit message in GitHub when
  merging a PR.

- "rebase-merge" is not a true rebase on GitHub, it results in a fast-forward merge just like "squash-merge".

- If a PR contains multiple commits, they will land as-is on `master` and show up in the changelog correctly, so we can have a `fix` and `feat` in the same PR.

- If a PR contains a single commit, it will also land as-is on `master`.

- It is up to the developer to decide if a PR should be squashed before merging it, and that will need to be done locally.

- Locally squashing has the added safety net of re-running the semantic commit checks, something the "squash-merge" in GitHub cannot do.

## Repos and rationale:

1. `dhis2/cli-style`: small and self-contained repo, used to verify that Dependabot can still merge PRs, and has automatic release to NPM.

2. `dhis2/app-store`: self-contained and works with feature branches, has automatic deployment to production on AWS.

3. `dhis2/ui-core`: Automatically deploys to NPM, has a lot of activity in all types (fix, feature, breaking changes), and has an upcoming `next` branch with many commits that will land and be documented in the changelog.

## Known issues and workarounds:

- Do not leave a comment saying "@dependabot squash and merge" when approving a Dependabot PR. We only need to give it an approving review with an empty comment to signal to Dependabot to merge the PR. If we tell it to "squash and merge" on a "rebase and merge" PR, then Dependabot remembers that forever, and it will always fail to squash-merge it.

  **Workaround** is to manually hit merge.

- When using the GitHub feature to "Update branch" with `master`, GitHub creates a merge commit with a non-semantic commit message like "Merge branch '{branch}' into {branch}". The Semantic Pull Requests bot is going to see that the branch now has a non-semantic commit and will not let you merge that to master.

  **Workaround** if the merge commit is the last commit is to update your branch locally using a semantic commit message, or, locally changing the non-semantic commit message through something like: `git commit --amend && git push origin HEAD --force-with-lease`.

  If there are multiple merge commits in your history of the branch, you need to rebase the branch with `rebase --interactive`, find the commits that are not semantic, and **(A)** `edit` them, or **(B)** `squash` them with the previous commit.

  If not familiar with `rebase` see: https://help.github.com/en/articles/about-git-rebase 

- When squashing commits locally we lose the possibility to see the individual commits forever, in a squash-merge workflow you could see the individual commits before they got squashed in the PR.

  **Workaround** is available to the developer that did the squash using reflog, but it's not distributed to other devs.

- If a developer realises after squashing that she needs to split out something to a separate commit, that is trickier to do than in a squash-merge workflow.

  **Workaround** is available using reflog, but may feel arcane to developers.

**Comment by Birkbjo** [comment]
> Workaround is to update your branch locally using a semantic commit message, or, locally changing the non-semantic commit message through something like: git commit --amend && git push origin HEAD --force-with-lease.

I just had a situation where I have multiple 'merges' from master into the feature branch, so this is not possible to do. It's also not straightforward to squash this branch now, as I have a lot of commits from master. I think we should avoid using the 'Update branch' feature when using this workflow, and manually rebase the branch instead, so we always have all the commits on top of master.

**Comment by varl** [comment]
> I think this shows that we should allow squash-merging again. In my opinion there's a lot more downsides to this than 'having two strategies'.

There are some changes to how the developers work in this strategy, but let's give it more than 2 days to adapt. There are some real problems related to arbitrarily squashing commits as well, related to how the conventional commit spec works.

Going over a lot of our commits and we will find that we are very lazy about writing good commit messages when squashing, the standard approach is accepting the default message GitHub provides and deeming that "good enough".

There's no denying that squash-merges are simple(r) for developers. We haven't done a good job handling that simplicity though, as we should be writing way better commit messages when squash-merging.

**Comment by Birkbjo** [comment]
It may have been a bit hasty to claim this, but I was in the middle of frustration as I had to rebase the branch and pick just the commits the PR introduced (commenting out like 15 commits form the merges (yes I used multiline editimg)). This is also kind of risky, as it's very easy to miss a commit you want. I then rebased master to update the branch.

So this was because 'Update branch' had been used multiple times before this workflow was introduced, so it may just he a matter of adjusting to the workflow.


However, I believe there's a difference between libs and standalone apps. In our relatively young libs there will be more breaking changes than in an app, and the changelog is overall more important - as there are dependents. In an app you don't really care if you switched out a component for another one - you mainly want to communicate bug fixes and new features to users. That's why I believe a lot of commits will just bloat the changelog (and history) if we start using this workflow.

> the standard approach is accepting the default message GitHub provides and deeming that "good enough".

To be honest, before the meeting agenda about this I thought semantic release would parse semantic commits within a squash commit and add them to the changelog.

**Comment by varl** [comment]
> However, I believe there's a difference between libs and standalone apps. In our relatively young libs there will be more breaking changes than in an app, and the changelog is overall more important

We are going to continuously release our apps on the App Store, and the changelog is going to be an important tool to verify what changed in the new version; both for quality assurance from our side, but also to get implementations to accept app upgrades.

**Comment by varl** [comment]
An example of a squashed commit message that is _not_ conventional commit compliant:

![image](https://user-images.githubusercontent.com/185449/67263360-2f7e4c00-f4a8-11e9-943e-a05953c7b726.png)

The breaking change note is now in the body of the commit message, which means that the breaking change will not be picked up by semantic release / conventional commits:

>BREAKING CHANGE: a commit that has a footer BREAKING CHANGE:, or appends a ! after the type/scope, introduces a breaking API change (correlating with MAJOR in semantic versioning). A BREAKING CHANGE can be part of commits of any type.

[Source](https://www.conventionalcommits.org/en/v1.0.0/#summary)

It would be damaging to diverge from the Conventional Commits standard and implement our own parser for commit messages to extract the breaking changes from a squashed commit. We would lose interoperability with all standards based tools, now and in the future.

We can enforce the messages we write at commit time, but GitHub can do whatever it wants when committing/merging.

**Comment by varl** [comment]
Using `semantic-release` it is recommended to not squash commits and instead be disciplined about the fact that one commit equals exactly one functional change[1]:

>Note: if the resulting squashed commit would encompasses multiple changes (for example multiple unrelated features or fixes) then it's probably not a good idea to squash those commits together. A commit should contain exactly one self-contained functional change and a functional change should be contained in exactly one commit. See atomic commits.

Atomic commits: https://en.wikipedia.org/wiki/Atomic_commit

[1] https://github.com/semantic-release/semantic-release/blob/master/docs/support/troubleshooting.md#squashed-commits-are-ignored-by-semantic-release

**Comment by varl** [comment]
It is possible to release to distribution channels using semantic-release, which is great. However, it does not work correctly when using **rebase-merge** or **squash-merge**, it only works when the commit hashes are kept intact, which means using a normal **merge** strategy.

The reason is that when releasing from `next`, semantic-release creates a version tag, e.g. `v2.0.0` and pushes that version as `@next` on NPM.

When `next` is then merged to `master`, the commit hash that `v2.0.0` points (which was taken from `next`) to must match the commit that lands on `master`, or else semantic-release will attempt to create the same `v2.0.0` tag but based on another commit hash, even though it's the "same" changes. It will then fail, and not publish the `v2.0.0` version to the `@latest` dist tag on NPM.

More information about the workflows here: https://github.com/semantic-release/semantic-release/blob/0785a844fa8ac1320383452ce531898be3b01f92/docs/recipes/distribution-channels.md#adding-a-version-to-latest

**Comment by varl** [comment]
In light of the above, we am testing out the **merge** workflow on the following repos:

- [dhis2/ui and friends](https://github.com/dhis2/ui)
- [dhis2/cli and friends](https://github.com/dhis2/cli)

**Comment by varl** [comment]
Given the wishlist in the first post:

> * Linear history on `master` (no merge commits)
> * One commit per feature/fix
> * Option for bundling changes for a release
> * Precise changelogs

I think we have to relax the requirement on a linear history and accept merge commits on `master` to properly leverage the semantic-release tool we use.

**Comment by Birkbjo** [comment]
> I think we have to relax the requirement on a linear history and accept merge commits on `master` to properly leverage the semantic-release tool we use.

Cool! I've missed references to pull requests from rebased PRs already. Will be nice to have the entire history there, even though it will be different to see all the merge commits again.

**Comment by varl** [comment]
The comments listed below can be considered the proposed result of this trial:

- https://github.com/dhis2/notes/issues/72#issuecomment-599187620
- https://github.com/dhis2/notes/issues/72#issuecomment-599199713

The merge workflow semantic-release has developed has proven to work very well.

There are some aesthetic down-sides in terms of the Git history in the GitHub user interface (https://github.com/dhis2/notes/issues/72#issuecomment-599383502) when forfeiting a linear commit history.

The functional improvements and features we get access to for free should outweigh the aesthetics.

**Comment by Birkbjo** [comment]
So are we blocking `squash and merge`? For big features with lots of commits it would make sense to just get one commit with `feat: a new feature` instead of all the commits in the PR. Do we do this manually with `rebase -i` and then force-push like with the rebase-approach, and thus loosing the commit history in that PR? 
You also have this that could help squashing big PRs: https://github.com/marketplace/actions/autosquash

**Comment by varl** [comment]
> So are we blocking `squash and merge`?

We don't have to.

I am in favor of only allowing one merge strategy in GitHub though, and the only one that consistently works is **merge**.

That said, if we want the **squash and merge** option, then **there are rules we MUST follow**:

- **Squash and merge** feature branches into a _single_ release branch is allowed:

- **Squash and merge** to maintenance branches like `v32` or `v1.x` is allowed.

- **_NEVER_** **squash and merge** a feature branch into _multiple_ release branches.

 You may **squash and merge** the branch `feat/my-nifty-feature` to a single commit that lands on `next`, and then **merge** `next` to `master`; the same commit SHA is on both release branches and `semantic-release` works fine.

You may also **squash and merge** your feature branch to `master` instead of `next`, but then you **MUST NOT** squash and merge your feature branch to `next`. The commit hash MUST stay the same from this point!

You may **NOT** allow the commit hash for a single feature to change once it has landed on a **release branch** as defined by `semantic-release`. Release branches are merged to and from each other using the **merge** strategy only.

---

This is not about what we can do with just Git and/or GitHub and/or what is aesthetically cleaner. `semantic-release` has well-written recipes for how to manage releases and the tools to support those processes.

I recommend reading up on `semantic-release` and the recipes they have designed their tools for:

- [Pre-releases: `@alpha`, `@beta`](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/pre-releases.md)

- [Distribution channels: `@next`](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/distribution-channels.md)

- [Maintenance versions: `v1.x`, `v2.1.x`](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/maintenance-releases.md)

Both **pre-releases** and **distrubution channels** needs the commit hash intact to figure out what commit is released on which branch as they are based on e.g. merging `master` into `next` or `next` into `master` to keep the branches in sync.

Since the commit hashes never change in a **merge** `semantic-release` can keep track of what is released where and update the changelogs, releases on GitHub, tags, and dist-tags on e.g. NPM accordingly.

For **maintenance versions**, it is possible to use **squash and merge** or another strategy that rewrites the commit hash (cherry-pick, for example). This is because the maintenance branch will never be merged to another branch, it lives its own life.

We are going to want to use the **pre-release** and **distribution channel** features for our apps and libraries though, so the simplest option is to stick to the **merge** strategy.

I refer back to points 4, 5, 6 from the rationale: https://github.com/dhis2/notes/issues/72#issuecomment-599199713

> * Not reinventing the wheel and leveraging the tools we have chosen. Semantic-release is stable and has worked out a good release regime. Instead of fighting it by using other workflows (squash/rebase), let's use the one they have built the software to support.
> 
> * Instead of encouraging developers to fix their bad commit messages retroactively, let's encourage them to write good commit messages by default.
> 
> * When fixing up code after code review, use `refactor:` or `chore:` commit types to hide the commits from the CHANGELOG instead of **squash-merges**.

Short answer to the commit history question: 

>Do we do this manually with `rebase -i` and then force-push like with the rebase-approach, and thus loosing the commit history in that PR?

You only lose the history if you write a bad commit message when rebasing. If you choose to squash your commits, you should write a commit message that covers all the changes that final commit does. In a big feature, that can be quite difficult to do well.

**Comment by varl** [comment]
After running this experiment for a year we have enough understanding about this topic to settle this.

The reality is that the different merge strategies are useful in different situations, so enforcing a single one is not a pragmatic approach.

As we are using `semantic-release` in our tools, aligning to the workflows they have developed and provide recipes for provides a good way forward. These recipes are proven to work over time:

- [Publishing on distribution channels](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/distribution-channels.md) (`latest`, `next`)
- [Publishing maintenance releases](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/maintenance-releases.md) (`1.x`, `35.x`, `1.2.x`)
- [Publishing pre-releases](https://github.com/semantic-release/semantic-release/blob/master/docs/recipes/pre-releases.md) (`alpha`, `beta`)

Different use cases in those recipes require different merge strategies, so to be able to utilize them we need to keep our merge options open, and instead focus on using the correct merge strategy for the use case.

This means that developers need to understand the release process so they know what to use when, and we should focus our efforts on that.
