### ISSUE TITLE
One repository with all tests VS tests with their respective repository

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/notes#74]
Splitting this off #54 

We've already had some discussions about where we want to put our tests.
I don't remember that we've reached a conclusion yet and agreed that - for now - we'll put the tests into the repositories where the tested code lives.

@varl has already mentioned that he'd prefer to collect them in those repositories:

> I think that converting our Zephyr test cases is a manual process, and the tests should be coded by hand, and pushed back to the application repository where the source code for the app lives.

He has also added a diagram of what a process that covers the whole DHIS 2 domain could look like:

![DHIS 2 testing process](https://user-images.githubusercontent.com/185449/60961542-b69a2080-a30c-11e9-98f7-030eb934b79b.png)

I like this approach and think it's easier to do if the tests live together with the code that will be tested

**Comment by varl** [comment]
# Proposal

- Tests should live with the Application.

- We should produce TAP compatible test reports.

- We should provide a way to consolidate all tests so they can be run as a single verification suite for QA.

**Comment by ismay** [comment]
What does TAP compatibility mean here exactly? I've found this: http://testanything.org. Is it something that can subsequently be parsed by QA?

**Comment by varl** [comment]
> What does TAP compatibility mean here exactly? I've found this: http://testanything.org. Is it something that can subsequently be parsed by QA?

Ah, yes. TAP is a protocol that is commonly used in testing, there are TAP producers for all of the languages that we use at DHIS2, and is simple to parse and generate full reports from. I've discussed it with QA, but the question is if we can use it with e.g. Jest / Cypress / jUnit / etc.

So the result can be that we agree that we **should, but cannot**. By reaching a consensus that we **should** at least is helpful. We may find other ways to the goal.

**Comment by ismay** [comment]
Ah, I see. Thanks for explaining!
