### ISSUE TITLE
Frontend Decision Board: December 18, 2019

### ISSUE THREAD

**Issue by varl** [dhis2/notes#81]
# FEDB December

Date: 2019-12-18

### One repository with all tests VS tests with their respective repository (#74)

Proposal: https://github.com/dhis2/notes/issues/74#issuecomment-563938270

### `data-test-id` attributes on all elements in the react (and other?) apps (#54)

Proposal: https://github.com/dhis2/notes/issues/54#issuecomment-563937288

### What to use for CSS styling in apps/components (#79)

Proposal: https://github.com/dhis2/notes/issues/79#issuecomment-563933328

**Comment by ismay** [comment]
So there's discussion on the data-test attributes here: https://dhis2.slack.com/archives/CBM8LNEQM/p1575274441006700 (and above it as well) and the PR https://github.com/dhis2/ui-core/pull/641 has discussion (and links to more) as well. I think that's all of it
