### ISSUE TITLE
data-test attribute naming convention

### ISSUE THREAD

**Issue by ismay** [dhis2/notes#88]
We now have data-test attributes in [ui-core](https://github.com/dhis2/ui-core), [app-hub](https://github.com/dhis2/app-hub), [ui-widgets](https://github.com/dhis2/ui-widgets) and [import-export](https://github.com/dhis2/import-export-app/). The naming conventions are still a bit different though, so the intention of this issue is to decide on a naming convention here, so we can implement it uniformly everywhere (see https://github.com/dhis2/import-export-app/pull/333#issuecomment-571478597).

### Libraries

My proposal is to use the pattern we've used in ui-core for libraries, which is:

```
dhis2-<libraryname>-<exportedcomponentname>-<optionalchild>
```

So for example, for the Chip that would be `dhis2-uicore-chip`, for the remove button on the chip it's `dhis2-uicore-chip-remove` and for the multiselect it's `dhis2-uicore-multiselect`. So the pattern is:

* All lowercase
* No dashes in the library-name, component-name and optional child-names (otherwise it can turn into a whole mess of dashes and it's not clear what's a dash in the original name and what's a dash to indicate hierarchy)
* The exported component accepts a dataTest prop which sets this part: `dhis2-uicore-<exportedcomponentname>` and then any optional child names are hardcoded in the component itself and appended to the dataTest prop. (that simplifies configuration, since allowing the children to be set as well can become complicated and doesn't seem necessary)
* We set a default for the dataTest prop according to the pattern defined above
* In adding the child data-test attributes we add them based on functionality, not html structure. That way test will keep working if the html changes and functionality stays the same, but tests will fail if the functionality changes/was removed and a test still tries to use it.
* Add child data-test attributes: for easier targeting of action triggers (X's on chips, etc.), to distinguish between duplicate siblings that would otherwise have identical data-test attributes (multiple help components, multiple buttons, etc.) or to allow finding components that are rendered in portals (there might be other useful scenarios as well)

### Apps

For apps I think the main reason for sticking to a convention for the data-test attributes is to keep things predictable for devs moving between apps, so that they can rely on a single convention. If we want to keep things similar to what we do with libraries (which seems the easiest), we could go with:

```
dhis2-<appname>-<componentname>-<optionalchild>
``` 

Plus the other points from above. I think we can basically use the same conventions here as for libraries, other than that we use the appname instead of the library name after `dhis2-`. What does everyone think of this proposal? Ideas, feedback, etc?

**Comment by Mohammer5** [comment]
:100: on board!

**Comment by jenniferarnesen** [comment]
Hi, I'm wondering about how to specifically identify elements in an app. Example. In data-visualizer there is a dialog for choosing dimensions. These dialogs have an Update and a Hide button, both are from ui-core:

![image](https://user-images.githubusercontent.com/6113918/77609399-1ce7c300-6edd-11ea-9091-9d1846a84974.png)

I currently can't tell the difference between them using data-test attribute - they both have the same `dhis2-uicore-button`.  So the alternative is to do something look at the button text. Any thoughts on this?

**Comment by Mohammer5** [comment]
@jenniferarnesen I'm moving this to a new issue as it's off topic

**Comment by Mohammer5** [comment]
I think this is more or less accepted now (and even baked into the `@dhis2/cli-utils-cypress` library. Could be closed/converted into some form of docs that apply to the whole dhis2 platform.

**Comment by amcgee** [comment]
Would it make sense to factor this out somehow?  It seems like a lot of duplicated code to do this in every component (similarly for `className` props, which require perhaps even more boilerplate when using `css.resolve`)

**Comment by amcgee** [comment]
(Very onboard with the suggestion and the attribute format, nice writeup @ismay!)

**Comment by amcgee** [comment]
A babel plugin could automate a lot of this, potentially

**Comment by Mohammer5** [comment]
You to transform it automatically and and add the prefix (possibly defined in `d2.config.js`)?

**Comment by ismay** [comment]
> Would it make sense to factor this out somehow? It seems like a lot of duplicated code to do this in every component (similarly for `className` props, which require perhaps even more boilerplate when using `css.resolve`)

If we want to automate this I'd tend towards simple helper functions, so that it stays transparent and easy to understand. Say, one for libs and one for apps, which enforce the naming pattern. For apps we could bundle it with the app platform. We could preset the prefixes we already know in the app platform (`dhis2` and the app name), to keep things simple.
