### ISSUE TITLE
TApps Meeting February 2020

### ISSUE THREAD

**Issue by varl** [dhis2/notes#89]
Hi @dhis2/team-apps :wave: 

It is time to gather around ~our microphones and webcams~ IRL (!) to take a moment to align. JIRA is good at managing bits and bobs of work in varying sizes, but one thing it does not do well is provide complete context of how everything fits together.

Below is an agenda for the meeting, and simultaneously an overview of the current situation. If I missed anything, please let me know.

---

# Agenda

## Long-term goals (2019-2022 ed.)

These are the high-level objectives that I have discussed with @larshelge, which we presented to the management team last year. 

- [ ] App continuous deployment [DHIS2-4394](https://jira.dhis2.org/browse/DHIS2-4394)
  This is related to a lot of things, not least the App Platform, App Hub, D2, DHIS2 Core changes,  ...
- [x] Rewrite app ~store~ hub backend in node js [HUB-26](https://jira.dhis2.org/browse/HUB-26)
  The rewrite of the v1 API is complete, and the infrastructure is running on AWS:
  - https://staging.apps.dhis2.org
  - https://apps.dhis2.org
  This only implies that the port is complete, not that the app hub is feature complete and rolled out to instances world-wide.
- [x] Components and documentation/portal, externalization
  We have the frameworks for all of these parts now, and we contributing to them is an on-going process, and on that premise, this can be considered completed.
- [ ] Maintenance app refactor [TECH-223](https://jira.dhis2.org/browse/TECH-223)
- [ ] Remove struts usage [DHIS2-8115](https://jira.dhis2.org/browse/DHIS2-8115)
- [x] Reports app
- [ ] Approval app [DHIS2-5973](https://jira.dhis2.org/browse/DHIS2-5973) 
- [ ] SMS app
- [ ] New app portal
  The idea is that the App Platform is going to morph into a replacement for the (Struts) web portal.

## Contextualizing and organizing work

We should be able to organize our work so that it aligns with the high-level objectives that we as a team have. We should also be able to track progress against each of these objectives that from now on are referred to as "projects".

As a start I have added an "epic" swimlane at the top of our [board](https://jira.dhis2.org/secure/RapidBoard.jspa?rapidView=102) that lists the Epic tasks that we are working on. The idea is that most of the tasks should support those tickets.

#### Approval App

Includes a new application for approval workflows: [DHIS2-5973](https://jira.dhis2.org/browse/DHIS2-5973)

#### SMS App

Includes a new application for SMS/Mobile configuration. 

### On-going projects

These are the things I know we are working on at the top of my head, let me know below if I have missed anything.

#### Application platform

Includes:

- app-platform
- app-runtime
- cli-app-scripts
- ui-core
- ui-widgets
- ui-forms

Includes porting existing applications to the application platform.

#### Continuous App Delivery

Includes:

- cli-utils-release
- app-hub
- app-management-app
- dhis2-core

Includes publishing existing applications to the App Hub and integrating it into our workflow.

#### Maintenance App Refactor

Includes:

- maintenance-app
- mar-y

#### Scheduler App Refactor

PR: https://github.com/dhis2/scheduler-app/pull/23

Includes:

- scheduler-app
- ui-core components

#### Testing & Stability

Includes:

- E2E tests for all components and apps
- Unit testing
- Cucumber specs to replace Zephyr test cases
- Cucumber feature files to provide acceptance criteria for features before work starts
- Infrastructure to run E2E and Unit tests on PRs
- Creating a common configuration and setup tool for testing (e.g. @dhis2/cypress or something).

#### Sunset core-resource-app

https://jira.dhis2.org/browse/TECH-91

Includes:

- Moving all apps away from linking to it
- Bundling deps in apps to make them standalone
- Removing core-resource-app from dhis2-core

**Comment by ismay** [comment]
Should we add the scheduler refactor to this?

**Comment by HendrikThePendric** [comment]
Oh yeah, and along the same line: It was mentioned [here](https://community.dhis2.org/t/dhis-version-2-33-is-released/37146/47) that we should also try to **deliver a new data-approval app for 2.34**. I think that would also fall under our jurisdiction right?

**Comment by varl** [comment]
I have a [Lay of the Land](https://dhis2.vardevs.se/layoftheland.html) page (updated 2020-01-08) that I use to look at the current situation. Might be of interest in this context.

**Comment by varl** [comment]
> Should we add the scheduler refactor to this?

Yes, let's include everything we are working on so that we have it "on the table" when organizing the work.

**Comment by varl** [comment]
> Oh yeah, and along the same line: It was mentioned [here](https://community.dhis2.org/t/dhis-version-2-33-is-released/37146/47) that we should also try to **deliver a new data-approval app for 2.34**. I think that would also fall under our jurisdiction right?

Yeah, it would. I've added it and SMS App under "Pipeline" since we haven't started it and don't have any specs. I have a meeting with @larshelge next week about it, we'll update the JIRA issue with more info.

**Comment by Mohammer5** [comment]
I started refactoring some import-export pages over the christmas & new years eve days. I'm not 100% finished with that yet (although it won't take too long I think, but I won't put all my focus on getting that done before other tasks as there are other things that are more important)

**Comment by ismay** [comment]
Actually, the Data Table is a crucial part of the new scheduler app design. When that's done the scheduler app refactor can continue. We could add it under the scheduler app todo (in the top comment here I mean).
