### ISSUE TITLE
data-test attribute as class names

### ISSUE THREAD

**Issue by Mohammer5** [dhis2/notes#90]
Currently, we're using the `data-test` attribute to denominate elements, which is great for testing.
But it comes with the slight disadvantage of being able to assign one value.

So I thought about why we're not using class names and prefix them with `datatest-` so it's obvious these class names should not change and should not be used for anything but testing.

It will simplify the selectors and allows multiple data-test values, so for example list items can have the value `datatest-dhis2-appname-listcomponent-item` as well as `datatest-dhis2-appname-specialname`.

It will just give us more flexibility and we wouldn't lose any existing benefits.

**Comment by Mohammer5** [comment]
I've added a branch/PR in the new maintenance app to demo what it could look like:
https://github.com/dhis2/mar-y/pull/108

**Comment by varl** [comment]
We are going to document use cases in code form, so that we can more easily gather our use cases and test them and figure out how to solve them.

Took photos off the whiteboard, will upload later.

**Comment by ismay** [comment]
So we don't forget, I think what we settled on in the end was to keep dataTest as is, and to add another prop that will allow appending extra strings to the `data-test` attribute. So:

```jsx
<Component
  dataTest="dhis2-component"
  dataTestSpecific="navigation"
/>
```

which would output:

```jsx
<div data-test="dhis2-component navigation" />
```

Then you could use this to select the component, as it's space-separated:

```
[data-test~="dhis2-component"] or [data-test~="navigation"]
```

That allows users to add a selector for specific targeting, whilst retaining the generic selectors.

**Comment by Mohammer5** [comment]
In addition, there's an attribute selector I wasn't aware of which enables us to select a specific data-test name when several are being provided:

```css
[data-test~="dhis2-libappname-datatestname"]
```

**Comment by varl** [comment]
>So we don't forget, I think what we settled on in the end was to keep dataTest as is, and to add another prop that will allow appending extra strings to the data-test attribute.

Didn't we settle on deferring doing this until we have better documentation over use cases and how often this is a problem?

**Comment by ismay** [comment]
Yes that's how I understood it. Just wanted to include the technical solution that we ended up with, if we want to do this later down the line.
